# 4 Numpy基础

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = my_list * 2

CPU times: user 14.8 ms, sys: 7.77 ms, total: 22.5 ms
Wall time: 22 ms
CPU times: user 115 ms, sys: 23.8 ms, total: 139 ms
Wall time: 139 ms


从上面的例子可以看到numpy很快。numpy快的原因：

- 数组在内存中连续存储。是独立于其他Python内置对象的
- 数组遍历不是用的python的for

## 4.1 ndarray

### ndarray数据类型

In [4]:
data = np.random.randn(2, 3)
data

array([[-0.94751937, -0.50654859, -1.64689355],
       [-0.21857883, -1.92045333, -1.06511562]])

In [5]:
data * 10

array([[ -9.47519369,  -5.06548592, -16.46893547],
       [ -2.18578831, -19.20453326, -10.65115618]])

In [6]:
data + data

array([[-1.89503874, -1.01309718, -3.29378709],
       [-0.43715766, -3.84090665, -2.13023124]])

In [19]:
data.shape

(2, 3)

### 4.1.1 生成ndarray

#### array

In [7]:
data1 = [6, 7, 5, 8, 0, 1]

In [8]:
arr1 = np.array(data1)

In [9]:
arr1

array([6, 7, 5, 8, 0, 1])

除array外，还有asarray, arange, ones, zeros, full, eye, identity等方法来生成数组

### 4.1.2 ndarray的数据类型

array在生成数组的时候会自动推断类型，也可以指定dtype参数显示指定类型

In [11]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [12]:
float_arr = arr.astype(np.float64)

In [13]:
float_arr.dtype

dtype('float64')

In [15]:
arr.dtype   # 注意原来的arr没有变。astype是返回了一个新的数组。

dtype('int64')

### 4.1.3 np数组运算

np数组可以直接运算，而无需用for遍历

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [19]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [20]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [21]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [22]:
arr < arr2

array([[False,  True, False],
       [ True, False,  True]])

### 4.1.4 基础索引与切片

于原生的切片不同，np的切片不会复制新的切片，而是返回一个引用。要想拷贝，可以显示调用`arr[2:4].copy()`

In [48]:
l1 = [1,2,3,4]
a = l1[1:2]
a[:] = [100]
l1

[1, 2, 3, 4]

In [49]:
arr1 = np.array([1,2,3,4])
b = arr1[1:2]
b

array([2])

In [50]:
b[:] = 100
arr1

array([  1, 100,   3,   4])