# ndarray

## N-Dimensional array(ndarray) in Numpy

In [1]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


## Array Creation

In [2]:
import numpy as np
 
# Creating array from list with type float
a = np.array([[1, 2, 4], 
              [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
 
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)
 
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
 
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


## Array Indexing

In [5]:
import numpy as np
 
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
 
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
print("cond:\n", cond)
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)
print("type(temp) = ", type(temp))

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]
cond:
 [[False  True False  True]
 [ True False  True False]
 [ True False  True  True]
 [ True False  True  True]]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]
type(temp) =  <class 'numpy.ndarray'>


## Basic operations

### Operations on single array

In [9]:
import numpy as np
 
a = np.array([1, 2, 5, 3])

print("original array:\n", a)
 
# add 1 to every element
print ("\nAdding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("\nSubtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("\nMultiplying each element by 10:", a*10)
 
# square each element
print ("\nSquaring each element:", a**2)
 
# modify existing array
a *= 2
print ("\nDoubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

original array:
 [1 2 5 3]

Adding 1 to every element: [2 3 6 4]

Subtracting 3 from each element: [-2 -1  2  0]

Multiplying each element by 10: [10 20 50 30]

Squaring each element: [ 1  4 25  9]

Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


### Unary operators

In [12]:
import numpy as np
 
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print ("\nLargest element is:", arr.max())

print ("\nRow-wise maximum elements:",
                    arr.max(axis = 1))     # 每一行最大的元素
 
# minimum element of array
print ("\nColumn-wise minimum elements:",
                        arr.min(axis = 0)) # 每一列最小的元素
 
# sum of array elements
print ("\nSum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("\nCumulative sum along each row:\n",
                        arr.cumsum(axis = 1))


Largest element is: 9

Row-wise maximum elements: [6 7 9]

Column-wise minimum elements: [1 1 2]

Sum of all array elements: 38

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


### Binary operators

In [13]:
import numpy as np
 
a = np.array([[1, 2],
            [3, 4]])

b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


### Universal functions (ufunc)

In [18]:
import numpy as np
 
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])  # [0, π/2, π]
print('a: \n', a)

print ("\nSine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("\nExponent of array elements:", np.exp(a))
 
# square root of array values
print ("\nSquare root of array elements:", np.sqrt(a))

a: 
 [0.         1.57079633 3.14159265]

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]

Square root of array elements: [0.         1.         1.41421356 1.73205081]


## Data Type

dtype包括几个部分

- Type of the data (integer, float, Python object etc.)
- Size of the data (number of bytes)
- Byte order of the data (little-endian or big-endian)
- If the data type is a sub-array, what is its shape and data type.

In [19]:
import numpy as np
 
# np.int16 is converted into a data type object.
print(np.dtype(np.int16))

int16


In [20]:
import numpy as np
 
# i4 represents integer of size 4 bytes
# > represents big-endian byte ordering and
# < represents little-endian encoding.
# dt is a dtype object
dt = np.dtype('>i4')
 
print("Byte order is:",dt.byteorder)
 
print("Size is:",dt.itemsize)
 
print("Data type is:",dt.name)

Byte order is: >
Size is: 4
Data type is: int32
